CREATE TABLE `editeur` (
  `Nom` VARCHAR(255) NOT NULL,
  `Adresse` VARCHAR(255) DEFAULT '',
  PRIMARY KEY (Nom)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;